ingress-nginx:
  controller:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: ndsquared.net
external-dns:
  provider: digitalocean
  digitalocean:
    apiToken: notarealtoken
  policy: sync
metrics-server:
  apiService:
    create: true
  extraArgs:
    kubelet-preferred-address-types: InternalIP
