name: Pulumi CI
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.11
      - run: poetry install
      - run: poetry run pulumi stack select dannylongeuay/do-infra/ndsquared
      - name: poetry run pulumi preview
        run: |
          PULUMI_PREVIEW=$(poetry run pulumi preview)
          echo "PULUMI_PREVIEW<<EOF" >> $GITHUB_ENV
          echo "$PULUMI_PREVIEW" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ env.PULUMI_PREVIEW }}
